GET localhost:3000/api/v1/bags/all

###
GET localhost:3000/api/v1/bags/1
###
POST localhost:3000/api/v1/bags/new
Content-Type: application/json

{
  "id": 1,
  "isSurprise": false,
  "listItem": { "pear": 5, "apple": 2 },
  "price": 50,
  "storeId": null,
  "date": 1741910400000,
  "size": "M",
  "status": "reserved"
}